2025-09-19 17:12:13,108 INFO    MainThread:16272 [wandb_setup.py:_flush():81] Current SDK version is 0.21.4
2025-09-19 17:12:13,108 INFO    MainThread:16272 [wandb_setup.py:_flush():81] Configure stats pid to 16272
2025-09-19 17:12:13,108 INFO    MainThread:16272 [wandb_setup.py:_flush():81] Loading settings from C:\Users\ДИзг\.config\wandb\settings
2025-09-19 17:12:13,109 INFO    MainThread:16272 [wandb_setup.py:_flush():81] Loading settings from E:\0workspace\AIPAI-TEST2-RL\wandb\settings
2025-09-19 17:12:13,109 INFO    MainThread:16272 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-09-19 17:12:13,109 INFO    MainThread:16272 [wandb_init.py:setup_run_log_directory():686] Logging user logs to E:\0workspace\AIPAI-TEST2-RL\wandb\run-20250919_171213-3nixhwz2\logs\debug.log
2025-09-19 17:12:13,109 INFO    MainThread:16272 [wandb_init.py:setup_run_log_directory():687] Logging internal logs to E:\0workspace\AIPAI-TEST2-RL\wandb\run-20250919_171213-3nixhwz2\logs\debug-internal.log
2025-09-19 17:12:13,109 INFO    MainThread:16272 [wandb_init.py:monkeypatch_ipython():605] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000015A54A63E50>
2025-09-19 17:12:13,109 INFO    MainThread:16272 [wandb_init.py:init():813] calling init triggers
2025-09-19 17:12:13,109 INFO    MainThread:16272 [wandb_init.py:init():818] wandb.init called with sweep_config: {}
config: {'env': 'ALE/Alien-v5', 'batch_size': 32, 'gamma': 0.99, 'lr': 0.0001, 'epsilon_start': 1.0, 'epsilon_end': 0.1, '_wandb': {}}
2025-09-19 17:12:13,110 INFO    MainThread:16272 [wandb_init.py:init():854] starting backend
2025-09-19 17:12:15,410 INFO    MainThread:16272 [wandb_init.py:init():857] sending inform_init request
2025-09-19 17:12:15,443 INFO    MainThread:16272 [wandb_init.py:init():865] backend started and connected
2025-09-19 17:12:15,447 INFO    MainThread:16272 [wandb_run.py:_label_probe_notebook():1330] probe notebook
2025-09-19 17:12:15,448 INFO    MainThread:16272 [wandb_run.py:_label_probe_notebook():1340] Unable to probe notebook: 'gbk' codec can't decode byte 0xa4 in position 3455: illegal multibyte sequence
2025-09-19 17:12:15,448 INFO    MainThread:16272 [wandb_init.py:init():936] updated telemetry
2025-09-19 17:12:15,504 INFO    MainThread:16272 [wandb_init.py:init():960] communicating run to backend with 90.0 second timeout
